#ifndef _OMNIPOWER_h
#define _OMNIPOWER_h

enum class Omnipower {
	DLMS = 0x41
};

enum class Omnipower_DLMS {
	ListSize,
	ListVersionIdentifier,
    CumulativeActiveImportEnergy_OBIS,
    CumulativeActiveImportEnergy,
	CumulativeActiveExportEnergy_OBIS,
	CumulativeActiveExportEnergy,
	CumulativeReactiveImportEnergy_OBIS,
	CumulativeReactiveImportEnergy,
	CumulativeReactiveExportEnergy_OBIS,
	CumulativeReactiveExportEnergy,
    MeterNumber_OBIS,
    MeterNumber,
	ActiveImportPower_OBIS,
	ActiveImportPower,
	ActiveExportPower_OBIS,
	ActiveExportPower,
	ReactiveImportPower_OBIS,
	ReactiveImportPower,
	ReactiveExportPower_OBIS,
	ReactiveExportPower,
	MeterClock_OBIS,
	MeterClock,
	VoltageL1_OBIS,
	VoltageL1,
	VoltageL2_OBIS,
	VoltageL2,
	VoltageL3_OBIS,
	VoltageL3,
	CurrentL1_OBIS,
	CurrentL1,
	CurrentL2_OBIS,
	CurrentL2,
	CurrentL3_OBIS,
	CurrentL3,
    ActiveImportPowerL1_OBIS,
    ActiveImportPowerL1,
    ActiveImportPowerL2_OBIS,
    ActiveImportPowerL2,
    ActiveImportPowerL3_OBIS,
    ActiveImportPowerL3,
    PowerFactorL1_OBIS,
    PowerFactorL1,
    PowerFactorL2_OBIS,
    PowerFactorL2,
    PowerFactorL3_OBIS,
    PowerFactorL3,
    PowerFactor_OBIS,
    PowerFactor,
    ActiveExportPowerL1_OBIS,
    ActiveExportPowerL1,
    ActiveExportPowerL2_OBIS,
    ActiveExportPowerL2,
    ActiveExportPowerL3_OBIS,
    ActiveExportPowerL3,
	CumulativeActiveExportEnergyL1_OBIS,
	CumulativeActiveExportEnergyL1,
	CumulativeActiveExportEnergyL2_OBIS,
	CumulativeActiveExportEnergyL2,
	CumulativeActiveExportEnergyL3_OBIS,
	CumulativeActiveExportEnergyL3,
    CumulativeActiveImportEnergyL1_OBIS,
    CumulativeActiveImportEnergyL1,
    CumulativeActiveImportEnergyL2_OBIS,
    CumulativeActiveImportEnergyL2,
    CumulativeActiveImportEnergyL3_OBIS,
    CumulativeActiveImportEnergyL3
};

#endif
