/**
 * @copyright Utilitech AS 2023-2026
 * License: Fair Source
 *
 * Decode tests over the unencrypted fixtures in test/payloads/.
 *
 * Strategy:
 *  - A golden-master sweep over EVERY unencrypted fixture (clean + edge). The
 *    expected decode of each frame is captured in expected_unencrypted.h
 *    (regenerate with: `program gen > test/test_decoder/expected_unencrypted.h`).
 *    This pins decoder behaviour: any change that alters how a real frame is
 *    decoded flips the test for review. Known meter quirks (e.g. the L&G
 *    integer-voltage frames, multi-segment frames that don't decode standalone)
 *    are captured as-is and documented in the payload READMEs.
 *  - A few explicit, human-readable assertions for well-understood frames.
 *
 * Fixture lists come from fixtures_generated.h (from test/payloads/manifest.json
 * via scripts/gen_fixtures_header.py).
 */
#include <unity.h>
#include <stdio.h>
#include <string.h>
#include "AmsData.h"
#include "decoder_harness.h"
#include "fixtures_generated.h"
#include "Timezone.h"
#include "crc.h"

#define COUNT(a) (sizeof(a) / sizeof((a)[0]))

struct Golden {
    const char* path;
    int decoded;        // 1 if a non-NULL AmsData was produced
    int listType, meterType;
    unsigned activeImport, activeExport;
    float l1v, l2v, l3v, l1a, l2a, l3a;
    double importCounter;
    const char* meterId;
};

#if __has_include("expected_unencrypted.h")
#include "expected_unencrypted.h"
#define HAVE_GOLDEN 1
#endif

// Emit the golden header to stdout (run the binary with the "gen" argument).
void harness_emit_golden(void) {
    printf("// AUTO-GENERATED by `program gen` — golden decode of unencrypted fixtures.\n");
    printf("// Review changes to this file: each line is how the decoder reads a real frame.\n");
    printf("static const Golden GOLDEN[] = {\n");
    const Fixture* lists[2] = { UNENC_OK, UNENC_EDGE };
    size_t counts[2] = { COUNT(UNENC_OK), COUNT(UNENC_EDGE) };
    for (int l = 0; l < 2; l++) {
        for (size_t i = 0; i < counts[l]; i++) {
            const char* path = lists[l][i].path;
            AmsData* d = harness_decode_fixture(path);
            if (!d) {
                printf("  { \"%s\", 0, 0,0, 0,0, 0,0,0, 0,0,0, 0, \"\" },\n", path);
            } else {
                printf("  { \"%s\", 1, %d,%d, %u,%u, %.2f,%.2f,%.2f, %.2f,%.2f,%.2f, %.3f, \"%s\" },\n",
                       path, d->getListType(), d->getMeterType(),
                       d->getActiveImportPower(), d->getActiveExportPower(),
                       d->getL1Voltage(), d->getL2Voltage(), d->getL3Voltage(),
                       d->getL1Current(), d->getL2Current(), d->getL3Current(),
                       d->getActiveImportCounter(), d->getMeterId().c_str());
                delete d;
            }
        }
    }
    printf("};\n");
}

void test_unencrypted_golden(void) {
#ifndef HAVE_GOLDEN
    TEST_IGNORE_MESSAGE("expected_unencrypted.h not generated yet (run: program gen > ...)");
#else
    int mismatches = 0;
    for (size_t i = 0; i < COUNT(GOLDEN); i++) {
        const Golden& g = GOLDEN[i];
        AmsData* d = harness_decode_fixture(g.path);
        bool ok = true;
        if ((d != NULL) != (g.decoded != 0)) ok = false;
        if (d && g.decoded) {
            if (d->getListType() != g.listType) ok = false;
            if (d->getMeterType() != g.meterType) ok = false;
            if (d->getActiveImportPower() != g.activeImport) ok = false;
            if (d->getActiveExportPower() != g.activeExport) ok = false;
            #define NEAR(a,b) (fabs((double)(a)-(double)(b)) <= 0.02)
            if (!NEAR(d->getL1Voltage(), g.l1v) || !NEAR(d->getL2Voltage(), g.l2v) ||
                !NEAR(d->getL3Voltage(), g.l3v)) ok = false;
            if (!NEAR(d->getL1Current(), g.l1a) || !NEAR(d->getL2Current(), g.l2a) ||
                !NEAR(d->getL3Current(), g.l3a)) ok = false;
            if (fabs(d->getActiveImportCounter() - g.importCounter) > 0.01) ok = false;
            if (strcmp(d->getMeterId().c_str(), g.meterId) != 0) ok = false;
            #undef NEAR
        }
        if (!ok) { printf("  GOLDEN MISMATCH: %s\n", g.path); mismatches++; }
        delete d;
    }
    char msg[64];
    snprintf(msg, sizeof(msg), "%d golden mismatches", mismatches);
    TEST_ASSERT_EQUAL_MESSAGE(0, mismatches, msg);
#endif
}

// ---- explicit, human-readable documentation tests ----

void test_iskra_am550_slovenia(void) {
    // Unencrypted Iskra AM550, Elektro Ljubljana (issue #956), 1s telegram.
    AmsData* d = harness_decode_fixture("test/payloads/iskraemeco/gh956-1.hex");
    TEST_ASSERT_NOT_NULL(d);
    TEST_ASSERT_EQUAL(AmsTypeIskra, d->getMeterType());
    TEST_ASSERT_GREATER_OR_EQUAL(1, d->getListType());
    TEST_ASSERT_FLOAT_WITHIN(5.0, 232.5, d->getL1Voltage());
    TEST_ASSERT_EQUAL_STRING("16820005", d->getMeterId().c_str());
    delete d;
}

void test_aidon_norway_list2(void) {
    // Aidon HAN-NVE hourly frame (issue #1119).
    AmsData* d = harness_decode_fixture("test/payloads/aidon/gh1119-1.hex");
    TEST_ASSERT_NOT_NULL(d);
    TEST_ASSERT_EQUAL(AmsTypeAidon, d->getMeterType());
    TEST_ASSERT_GREATER_OR_EQUAL(1, d->getListType());
    TEST_ASSERT_FLOAT_WITHIN(5.0, 233.0, d->getL1Voltage());
    delete d;
}

void test_dsmr_accepts_lf_and_crlf(void) {
    // A DSMR/P1 telegram must decode identically whether it uses CRLF (the P1
    // standard) or bare LF line endings.
    MeterConfig cfg; memset(&cfg, 0, sizeof(cfg));
    uint8_t crlf[4096]; int nc = harness_load_fixture("test/payloads/kamstrup/gh578-1.txt", crlf, sizeof(crlf));
    TEST_ASSERT_GREATER_THAN(0, nc);

    // Build an LF-only copy by dropping carriage returns. The DSMR CRC covers
    // the telegram bytes (line endings included), so a real LF meter computes
    // its CRC over LF content — recompute it here to make a valid LF telegram.
    uint8_t lf[4096]; int nl = 0;
    for (int i = 0; i < nc; i++) if (crlf[i] != '\r') lf[nl++] = crlf[i];
    TEST_ASSERT_TRUE(nl < nc);   // the fixture really was CRLF
    int bang = -1;
    for (int i = 0; i < nl; i++) if (lf[i] == '!') { bang = i; break; }
    TEST_ASSERT_GREATER_THAN(0, bang);
    char crc[5];
    snprintf(crc, sizeof(crc), "%04X", crc16(lf, bang + 1));
    memcpy(lf + bang + 1, crc, 4);   // overwrite the 4 CRC hex chars

    AmsData* a = harness_decode(crlf, (uint16_t)nc, &cfg, NULL, NULL);
    AmsData* b = harness_decode(lf,   (uint16_t)nl, &cfg, NULL, NULL);
    TEST_ASSERT_NOT_NULL(a);
    TEST_ASSERT_NOT_NULL_MESSAGE(b, "LF-only DSMR telegram failed to decode");
    TEST_ASSERT_EQUAL(a->getListType(), b->getListType());
    TEST_ASSERT_EQUAL(a->getActiveImportPower(), b->getActiveImportPower());
    TEST_ASSERT_FLOAT_WITHIN(0.01, a->getL1Voltage(), b->getL1Voltage());
    delete a; delete b;
}

void test_kamstrup_norway(void) {
    // Kamstrup unencrypted DLMS (Gunnar's own meter, email fixture).
    AmsData* d = harness_decode_fixture("test/payloads/kamstrup/em001-1.hex");
    TEST_ASSERT_NOT_NULL(d);
    TEST_ASSERT_EQUAL(AmsTypeKamstrup, d->getMeterType());
    TEST_ASSERT_GREATER_OR_EQUAL(1, d->getListType());
    TEST_ASSERT_FLOAT_WITHIN(5.0, 236.0, d->getL1Voltage());
    delete d;
}

// Expected UTC epoch from a broken-down UTC time (makeTime treats fields as UTC).
static time_t utc_epoch(int y, int mo, int da, int h, int mi, int se) {
    tmElements_t t;
    t.Year = y - 1970; t.Month = mo; t.Day = da;
    t.Hour = h; t.Minute = mi; t.Second = se; t.Wday = 0;
    return makeTime(t);
}

void test_kamstrup_timezone(void) {
    // Kamstrup reports its clock in local STANDARD time year-round (no DST
    // spring) with the UTC deviation left unspecified. The decoder must convert
    // to UTC by subtracting the configured zone's STANDARD offset, NOT a
    // hardcoded -3600 (which was only right for CET). See issue #1191.
    TimeChangeRule cetDst = {"CEST",0,0,3,2,120}, cetStd = {"CET",0,0,10,3,60};
    TimeChangeRule eetDst = {"EEST",0,0,3,3,180}, eetStd = {"EET",0,0,10,4,120};
    Timezone cet(cetDst, cetStd);   // standard offset +60 min
    Timezone eet(eetDst, eetStd);   // standard offset +120 min

    struct Case { const char* path; Timezone* tz; time_t expected; const char* note; };
    Case cases[] = {
        // Norway/CET, winter frame (wall 2021-11-25 23:00:55) -> -1h
        {"test/payloads/kamstrup/em001-1.hex", &cet, utc_epoch(2021,11,25,22,0,55), "Norway CET winter"},
        // Denmark/CEST, summer frame (wall 2023-04-06 13:49:50) -> still -1h (clock is CET all year)
        {"test/payloads/kamstrup/gh517-2.hex", &cet, utc_epoch(2023,4,6,12,49,50), "Denmark CEST summer"},
        // Finland/EET, summer hourly frame (wall 2026-05-25 17:00:55) -> -2h (standard EET offset)
        {"test/payloads/kamstrup/gh1191-1.hex", &eet, utc_epoch(2026,5,25,15,0,55), "Finland EET (#1191)"},
    };
    for (size_t i = 0; i < COUNT(cases); i++) {
        AmsData* d = harness_decode_fixture_tz(cases[i].path, cases[i].tz);
        TEST_ASSERT_NOT_NULL_MESSAGE(d, cases[i].path);
        TEST_ASSERT_EQUAL(AmsTypeKamstrup, d->getMeterType());
        time_t got = d->getMeterTimestamp();
        printf("  %-22s got=%ld expected=%ld (%+ld s)\n",
               cases[i].note, (long)got, (long)cases[i].expected, (long)(got - cases[i].expected));
        TEST_ASSERT_EQUAL_MESSAGE(cases[i].expected, got, cases[i].note);
        delete d;
    }
}
